export enum TOKEN_TYPE{
    START_OF_FILE = 0,
    END_OF_FILE,
    TAG_OPEN,
    TAG_CLOSE,
    TAG_CLOSE_SLASH,
    ASSIGNMENT,
    AT_THE_RATE,
    INTERPOLATION,
    STRING,
    SINGLE_QUOTE,
    DOUBLE_QUOTE,
    HASH,
    DOLLAR,
}

export const TOKEN_VALUE = {
    [TOKEN_TYPE.START_OF_FILE]: "START_OF_FILE",
    [TOKEN_TYPE.END_OF_FILE]: "END_OF_FILE",
    [TOKEN_TYPE.TAG_OPEN]: "<",
    [TOKEN_TYPE.TAG_CLOSE]: ">",
    [TOKEN_TYPE.TAG_CLOSE_SLASH]: "/",
    [TOKEN_TYPE.ASSIGNMENT]: "=",
    [TOKEN_TYPE.AT_THE_RATE]: "@",
    [TOKEN_TYPE.INTERPOLATION]: "INTERPOLATION",
    [TOKEN_TYPE.STRING]: "STRING",
    [TOKEN_TYPE.SINGLE_QUOTE]:"'",
    [TOKEN_TYPE.DOUBLE_QUOTE]:'"',
    [TOKEN_TYPE.HASH]:'#',
    [TOKEN_TYPE.DOLLAR]:'$'
};